import Foundation
import SwiftUI

// MARK: - Core Protocols

/// Protocol for all Assist tools.
/// All tools must be prefixed with 'Assist'.
public protocol AssistTool {
    var id: String { get }
    var name: String { get }
    var description: String { get }

    func execute(input: [String: Any], context: AssistContext) async throws -> AssistToolResult
}

// MARK: - Assist Context & State

/// Shared context provided to tools during execution.
public struct AssistContext {
    public let sessionId: UUID
    public let project: Project?
    public let workspaceRoot: URL
    public let memory: AssistMemoryGraphProtocol
    public let logger: AssistLoggerProtocol
    public let fileSystem: AssistFileSystemProtocol
    public let git: AssistGitManagerProtocol
    public let permissions: AssistPermissionsManagerProtocol

    // Safety & Mode settings
    public let safetyLevel: AssistSafetyLevel
    public let isAutonomous: Bool

    public init(
        sessionId: UUID,
        project: Project?,
        workspaceRoot: URL,
        memory: AssistMemoryGraphProtocol,
        logger: AssistLoggerProtocol,
        fileSystem: AssistFileSystemProtocol,
        git: AssistGitManagerProtocol,
        permissions: AssistPermissionsManagerProtocol,
        safetyLevel: AssistSafetyLevel,
        isAutonomous: Bool
    ) {
        self.sessionId = sessionId
        self.project = project
        self.workspaceRoot = workspaceRoot
        self.memory = memory
        self.logger = logger
        self.fileSystem = fileSystem
        self.git = git
        self.permissions = permissions
        self.safetyLevel = safetyLevel
        self.isAutonomous = isAutonomous
    }
}

/// Safety levels for autonomous execution.
public enum AssistSafetyLevel: String, Codable, CaseIterable {
    case conservative = "Conservative"
    case balanced = "Balanced"
    case aggressive = "Aggressive"
}

/// Result returned by an Assist tool execution.
public struct AssistToolResult: Codable {
    public let success: Bool
    public let output: String
    public let data: [String: String]?
    public let error: String?

    public init(success: Bool, output: String, data: [String: String]? = nil, error: String? = nil) {
        self.success = success
        self.output = output
        self.data = data
        self.error = error
    }

    public static func success(_ output: String, data: [String: String]? = nil) -> AssistToolResult {
        AssistToolResult(success: true, output: output, data: data)
    }

    public static func failure(_ error: String) -> AssistToolResult {
        AssistToolResult(success: false, output: "Error: \(error)", error: error)
    }
}

// MARK: - Planning & Execution Models

/// A structured plan generated by the AssistPlanner.
public struct AssistExecutionPlan: Codable, Identifiable {
    public let id: UUID
    public let goal: String
    public var steps: [AssistExecutionStep]
    public var status: AssistExecutionStatus

    public init(goal: String, steps: [AssistExecutionStep] = []) {
        self.id = UUID()
        self.goal = goal
        self.steps = steps
        self.status = .pending
    }
}

/// A single step within an execution plan.
public struct AssistExecutionStep: Codable, Identifiable {
    public let id: UUID
    public let toolId: String
    public let input: [String: String] // Simple key-value for storage/serialization
    public let description: String
    public var status: AssistExecutionStatus
    public var result: AssistToolResult?

    public init(toolId: String, input: [String: String], description: String) {
        self.id = UUID()
        self.toolId = toolId
        self.input = input
        self.description = description
        self.status = .pending
    }
}

public enum AssistExecutionStatus: String, Codable {
    case pending
    case running
    case completed
    case failed
    case skipped
}

// MARK: - Legacy / UI Compatibility Models

/// Maintained for UI compatibility during transition
public struct AssistModelOption: Identifiable, Codable, Hashable {
    public let id: String
    public let displayName: String
    public let provider: String

    public static let swiftCodeBalanced = AssistModelOption(id: "swiftcode.assist.balanced", displayName: "SwiftCode Balanced", provider: "SwiftCode")
    public static let swiftCodeReasoning = AssistModelOption(id: "swiftcode.assist.reasoning", displayName: "SwiftCode Reasoning", provider: "SwiftCode")
    public static let gpt4oMini = AssistModelOption(id: "openai.gpt-4o-mini", displayName: "GPT-4o mini", provider: "OpenAI")
    public static let claudeSonnet = AssistModelOption(id: "anthropic.claude-sonnet", displayName: "Claude Sonnet", provider: "Anthropic")

    public static let all: [AssistModelOption] = [.swiftCodeBalanced, .swiftCodeReasoning, .gpt4oMini, .claudeSonnet]
}

/// Maintained for UI compatibility
public enum AssistStatus: String, Codable {
    case pending
    case inProgress
    case completed
    case failed
    case rejected
}

public struct AssistMessage: Codable, Identifiable {
    public let id: UUID
    public let role: AssistRole
    public let content: String
    public let timestamp: Date

    public init(role: AssistRole, content: String) {
        self.id = UUID()
        self.role = role
        self.content = content
        self.timestamp = Date()
    }
}

public enum AssistRole: String, Codable {
    case user
    case assistant
    case system
}

public enum AssistCapabilityKind: String, Codable {
    case `extension`
    case skill
    case connection
}

// MARK: - Core Protocols for Components

public protocol AssistMemoryGraphProtocol {
    func store(key: String, value: String)
    func retrieve(key: String) -> String?
    func clear()
}

public protocol AssistLoggerProtocol {
    func info(_ message: String, toolId: String?)
    func warning(_ message: String, toolId: String?)
    func error(_ message: String, toolId: String?)
    func debug(_ message: String, toolId: String?)
}

public protocol AssistFileSystemProtocol {
    func readFile(at path: String) throws -> String
    func writeFile(at path: String, content: String) throws
    func deleteFile(at path: String) throws
    func moveFile(from: String, to: String) throws
    func copyFile(from: String, to: String) throws
    func exists(at path: String) -> Bool
}

public protocol AssistGitManagerProtocol {
    func status() throws -> String
    func commit(message: String) throws
    func push() async throws
}

public protocol AssistPermissionsManagerProtocol {
    func isPathAllowed(_ path: String) -> Bool
    func authorizeOperation(_ operation: String) -> Bool
}
